### ISSUE TITLE
Pass arguments to controller

### ISSUE THREAD

**Issue by wamaro** [Xocotlah/Router#2]
(How) Is it possible to use arguments for controller with this package or League/Route?
I search something like the following example:
```php
// route
$router->map('GET', '/users/{id:number}', [UserController::class, 'show', ['id']]);

// this should call (an option for 'call_user_func' || 'call_user_func_array' would be next question)
new UserController($request, $response, $router)->show($id);
```

**Comment by Arcesilas** [comment]
Hi,

Sorry for the delay.

Arguments are passed to the controller, since it's the case with League\Route. This package does not change anything about it.

But with your question, I've realized that it's not handled the best way and I should try to make it easier.

Currently, to get arguments, define your controller like this, for example:

```php
<?php

namespace App\Http\Controllers;

use Xocotlah\Router\Controller\BaseController;

class HelloController extends BaseController
{
    public function sayIt($request, $response, $args)
    {
        $this->response->getBody()->write('Hello '.$args['name'].'!');
        return $this->response;
    }
}
```

I've also been thinking that to not have to return the response but only the body should be easier...

I'll work on it soon. Hopefully, my answer will help you for now.

**Comment by wamaro** [comment]
This helped!
As your BaseController already holds $request and $response as class members via constructor, I didn't expect them to be passed to the function call again. Thank you for pointing out.
Looking forward to your work.

**Comment by Arcesilas** [comment]
That's the point... I did not think about this "problem"...
Thanks again for your interest :)

**Comment by Arcesilas** [comment]
Hi again,

I'm preparing a v0.2.0 with route parameters set into Controllers.
You may check it on `develop` branch, if you wish.

I still have to write tests for the new feature, but it seems ok AFAIK.
